version: "3"
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_HOST_AUTH_METHOD: trust
      
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    container_name: redis
    ports:
      - 6379:6379
    image: redis:6.2.5-alpine

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.16.2
    ports:
      - 9200:9200
      - 9300:9300
    labels:
      co.elastic.logs/json.overwrite_keys: true 
      co.elastic.logs/json.add_error_key: true 
      co.elastic.logs/json.expand_keys: true
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: kibana:8.16.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  aws-cli:
    image: amazon/aws-cli
    depends_on:
     localstack:
        condition: service_healthy
    volumes:
      - ./testbucket:/aws
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket my-bucket --region us-east-1
        aws --endpoint-url=http://localstack:4566 s3api ls s3://my-bucket --recursive --human-readable --summarize
      "
  ai_app:
    container_name: python_ai
    profiles:
      - ""
      - python
    depends_on:
      - localstack
    build: 
      context: ./apps/ai-service
      dockerfile: dev.Dockerfile
    volumes:
      - ./apps/frontend:/app
    ports:
      - 8000:8000 

  backend_app:
    container_name: backend_app
    profiles:
      - ""
      - backend
    build:
      context: ./apps/backend
      dockerfile: dev.Dockerfile
    env_file: apps/backend/.env
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - 4000:4000 
    depends_on:
      - localstack
      - postgres
      - rabbitmq
      - redis

  frontend_app:
    container_name: frontend_app
    profiles:
      - ""
      - frontend
    build:
      context: ./apps/frontend
      dockerfile: dev.Dockerfile
    env_file: apps/frontend/.env
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend_app
