apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: backend_app:latest
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: backend-volume
              mountPath: /app
          envFrom:
            - configMapRef:
                name: backend-env
      volumes:
        - name: backend-volume
          hostPath:
            path: ./apps/backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  ports:
    - port: 4000
  selector:
    app: backend-app
